//HintName: IStringLocalizerExtensions.Some.Root.Namespace.TR0002_NoCode.g.cs
// <auto-generated/>
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Some.Root.Namespace;
using Some.Root.Namespace.TypealizR;
namespace Microsoft.Extensions.Localization
{
    [GeneratedCode("TypealizR.StringLocalizerExtensionsSourceGenerator", "1.0.0.0")]
    internal static partial class IStringLocalizerExtensionsSomeRootNamespaceTR0002_NoCode
    {
        /// <summary>
        /// Looks up a localized string similar to 'Greetings {name:s}, today is {date:d}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Greetings {0}, today is {1}'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Greetings__name__today_is__date(this IStringLocalizer<global::Some.Root.Namespace.TR0002_NoCode> that, string name, DateOnly date)
            => that["Greetings {name:s}, today is {date:d}"].Format(name, date);
        /// <summary>
        /// Looks up a localized string similar to 'Greetings {name}, today is {date}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Greetings {0}, today is {1}'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Greetings__name__today_is__date1(this IStringLocalizer<global::Some.Root.Namespace.TR0002_NoCode> that, object name, object date)
            => that["Greetings {name}, today is {date}"].Format(name, date);
        /// <summary>
        /// wraps the specified <see cref="IStringLocalizer&ltSome.Root.Namespace.TR0002_NoCode&gt"/> into a generated type providing properties to access [Some.Nested.Group]: via properties
        /// IStringLocalizer<Some.Root.Namespace.TR0002_NoCode> localize = ...
        /// localize.Some.Nested.Group...
        /// </summary>
        [DebuggerStepThrough]
        public static TypealizedTR0002_NoCode Typealize(this IStringLocalizer<global::Some.Root.Namespace.TR0002_NoCode> that)
            => new TypealizedTR0002_NoCode(that);
    }
}