//HintName: IStringLocalizerExtensions.Some.Root.Namespace.TR0002_NoCode.g.cs
// <auto-generated/>
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Some.Root.Namespace;
using Some.Root.Namespace.TypealizR;
namespace Microsoft.Extensions.Localization
{
    /// <summary>
    /// Extensions for <see cref="Some.Root.Namespace.TR0002_NoCode"/> to utilize typed-access to ressources generated by TypealizR.
    /// </summary>
    [GeneratedCode("TypealizR.StringLocalizerExtensionsSourceGenerator", "1.0.0.0")]
    internal static partial class IStringLocalizerExtensionsSomeRootNamespaceTR0002_NoCode
    {
        /// <summary>
        /// Looks up a localized string similar to 'Greetings {name:s}, today is {date:d}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Greetings {0}, today is {1}'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Greetings__name__today_is__date(this IStringLocalizer<global::Some.Root.Namespace.TR0002_NoCode> that, string name, DateOnly date) => that[_Greetings__name__today_is__date].Format(name, date);
        private const string _Greetings__name__today_is__date = "Greetings {name:s}, today is {date:d}";
        /// <summary>
        /// Looks up a localized string similar to 'Greetings {name}, today is {date}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Greetings {0}, today is {1}'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Greetings__name__today_is__date1(this IStringLocalizer<global::Some.Root.Namespace.TR0002_NoCode> that, object name, object date) => that[_Greetings__name__today_is__date1].Format(name, date);
        private const string _Greetings__name__today_is__date1 = "Greetings {name}, today is {date}";
        /// <summary>
        /// wraps the specified <see cref="IStringLocalizer{TR0002_NoCode}"/> into a generated type providing properties to access [Some.Nested.Group]: via properties
        /// IStringLocalizer{TR0002_NoCode} localize = ...
        /// localize.Some.Nested.Group...
        /// </summary>
        [DebuggerStepThrough]
        public static TypealizedTR0002_NoCode Typealize(this IStringLocalizer<global::Some.Root.Namespace.TR0002_NoCode> that)
            => new TypealizedTR0002_NoCode(that);
    }
}