//HintName: IStringLocalizerExtensions.Some.Root.Namespace.Groupings_NoCode.g.cs
// <auto-generated/>
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Some.Root.Namespace;
using Some.Root.Namespace.TypealizR;
namespace Microsoft.Extensions.Localization
{
    /// <summary>
    /// Extensions for <see cref="Some.Root.Namespace.Groupings_NoCode"/> to utilize typed-access to ressources generated by TypealizR.
    /// </summary>
    [GeneratedCode("TypealizR.StringLocalizerExtensionsSourceGenerator", "1.0.0.0")]
    internal static partial class IStringLocalizerExtensionsSomeRootNamespaceGroupings_NoCode
    {
        /// <summary>
        /// Looks up a localized string similar to 'Greetings {name}, today is {date}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Greetings {0}, today is {1}'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Greetings__name__today_is__date(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that, object name, object date) => that[_Greetings__name__today_is__date].Format(name, date);
        private const string _Greetings__name__today_is__date = "Greetings {name}, today is {date}";
        /// <summary>
        /// Looks up a localized string similar to 'Hello'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Hello'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Hello(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that) => that[_Hello];
        private const string _Hello = "Hello";
        /// <summary>
        /// Looks up a localized string similar to 'Hello {name:s}, today is {date:d}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Hello {0}, today is {1}'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Hello__name__today_is__date(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that, string name, DateOnly date) => that[_Hello__name__today_is__date].Format(name, date);
        private const string _Hello__name__today_is__date = "Hello {name:s}, today is {date:d}";
        /// <summary>
        /// Looks up a localized string similar to '[Log.Critical]: Failed to delete {UserName:s}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Failed to delete {0}'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString LogCritical_Failed_to_delete__UserName(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that, string UserName) => that[_LogCritical_Failed_to_delete__UserName].Format(UserName);
        private const string _LogCritical_Failed_to_delete__UserName = "[Log.Critical]: Failed to delete {UserName:s}";
        /// <summary>
        /// Looks up a localized string similar to '[Log.Warning]: Could not find {UserName:s}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Could not find {0}'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString LogWarning_Could_not_find__UserName(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that, string UserName) => that[_LogWarning_Could_not_find__UserName].Format(UserName);
        private const string _LogWarning_Could_not_find__UserName = "[Log.Warning]: Could not find {UserName:s}";
        /// <summary>
        /// Looks up a localized string similar to '[Log.Warning]: Unknown error'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Encountered an unknown error during the operation'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString LogWarning_Unknown_error(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that) => that[_LogWarning_Unknown_error];
        private const string _LogWarning_Unknown_error = "[Log.Warning]: Unknown error";
        /// <summary>
        /// Looks up a localized string similar to '[Question]: Abort ?'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Abort?'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Question_Abort(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that) => that[_Question_Abort];
        private const string _Question_Abort = "[Question]: Abort ?";
        /// <summary>
        /// Looks up a localized string similar to '[Question]: Continue to delete {UserName:s}?'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Continue to delete {0}?'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Question_Continue_to_delete__UserName(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that, string UserName) => that[_Question_Continue_to_delete__UserName].Format(UserName);
        private const string _Question_Continue_to_delete__UserName = "[Question]: Continue to delete {UserName:s}?";
        /// <summary>
        /// Looks up a localized string similar to '[Warning]: {UserName:s} will be deleted!'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of '{0} will be deleted'
        /// </returns>
        [DebuggerStepThrough]
        public static LocalizedString Warning__UserName__will_be_deleted(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that, string UserName) => that[_Warning__UserName__will_be_deleted].Format(UserName);
        private const string _Warning__UserName__will_be_deleted = "[Warning]: {UserName:s} will be deleted!";
        /// <summary>
        /// wraps the specified <see cref="IStringLocalizer{Groupings_NoCode}"/> into a generated type providing properties to access [Some.Nested.Group]: via properties
        /// IStringLocalizer{Groupings_NoCode} localize = ...
        /// localize.Some.Nested.Group...
        /// </summary>
        [DebuggerStepThrough]
        public static TypealizedGroupings_NoCode Typealize(this IStringLocalizer<global::Some.Root.Namespace.Groupings_NoCode> that)
            => new TypealizedGroupings_NoCode(that);
    }
}