<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ExcludeFromCodeCoverage>true</ExcludeFromCodeCoverage>
        <IsPackable>false</IsPackable>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <SonarQubeExclude>true</SonarQubeExclude>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    
    <PropertyGroup>
        <!-- Update the property to include all EmbeddedResource files -->
        <AdditionalFileItemNames>$(AdditionalFileItemNames);EmbeddedResource</AdditionalFileItemNames>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\src\TypealizR.Analyzers.CodeFixes\TypealizR.Analyzers.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\src\TypealizR.Analyzers\TypealizR.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\src\TypealizR\TypealizR.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\src\TypealizR.Core\TypealizR.Core.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.10" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Strings.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Strings.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Strings.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>
   
    <ItemGroup>
        <Using Include="Microsoft.Extensions.DependencyInjection"/>
        <Using Include="Microsoft.Extensions.Localization"/>
        <Using Include="Microsoft.Extensions.Logging"/>
    </ItemGroup>
</Project>
