//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.Shared.Groups {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ressources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ressources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Playground.Shared.Groups.Ressources", typeof(Ressources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string _Messages_Info___Info1 {
            get {
                return ResourceManager.GetString("[Messages.Info]: Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string _Messages_Info___Info2 {
            get {
                return ResourceManager.GetString("[Messages.Info]: Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        public static string _Messages_Info___Info3 {
            get {
                return ResourceManager.GetString("[Messages.Info]: Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do?.
        /// </summary>
        public static string _Questions___What_to_do_ {
            get {
                return ResourceManager.GetString("[Questions]: What to do?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do {0}?.
        /// </summary>
        public static string _Questions___What_to_do__now__dt__ {
            get {
                return ResourceManager.GetString("[Questions]: What to do {now: dt}?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It.
        /// </summary>
        public static string _Some_Deeply_Nested_Thing_Called_After_A_Monster___It {
            get {
                return ResourceManager.GetString("[Some.Deeply.Nested.Thing.Called.After.A.Monster]: It", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the name.
        /// </summary>
        public static string _Some_Deeply_Nested_Thing_Called_After_A_Monster___With_the__name_s_ {
            get {
                return ResourceManager.GetString("[Some.Deeply.Nested.Thing.Called.After.A.Monster]: With the {name:s}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}.
        /// </summary>
        public static string Hello__world_s_ {
            get {
                return ResourceManager.GetString("Hello {world:s}", resourceCulture);
            }
        }
    }
}
