using System;
using System.Collections.Generic;
using System.Linq;

namespace TypealizR.SourceGenerators.StringLocalizer;

internal class ExtensionClassInfo
{
    private static string generatorName = nameof(TypealizR);
    private static Version generatorVersion = typeof(ExtensionClassInfo).Assembly.GetName().Version;

    private readonly string targetTypeName;
    private readonly string targetNamespace;

    private readonly string members;

    public ExtensionClassInfo(string targetTypeName, string targetNamespace, ExtensionMethodInfo[] methods)
    {
        this.targetTypeName = targetTypeName;
        this.targetNamespace = targetNamespace;

        members = string.Join("\r", methods
            .Select(x => x.Declaration)
            .ToArray()
        );
    }

    public string Declaration => $@"
// <auto-generated/>
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Localization;
using {targetNamespace};
namespace Microsoft.Extensions.Localization;
[
    GeneratedCode(""{generatorName}"", ""{generatorVersion}""),
    DebuggerStepThrough,
    ExcludeFromCodeCoverage(Justification = ""generated code"")
]
internal static partial class IStringLocalizerExtensions_{targetTypeName}
{{
{members}
}}
";
}