//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypealizR.Core.Diagnostics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypealizR.Core.Diagnostics.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code generator could not determine the projects root-directory.
        /// </summary>
        internal static string TR0001_Description {
            get {
                return ResourceManager.GetString("TR0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code generator could not determine the projects root-directory. See {0}.
        /// </summary>
        internal static string TR0001_MessageFormat {
            get {
                return ResourceManager.GetString("TR0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an ambigious resource-key.
        /// </summary>
        internal static string TR0002_Description {
            get {
                return ResourceManager.GetString("TR0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource-key &apos;{0}&apos; would end up as a duplicate method-name. Using &apos;{1}&apos; as derived name for this key. See {2}.
        /// </summary>
        internal static string TR0002_MessageFormat {
            get {
                return ResourceManager.GetString("TR0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered a generic parameter.
        /// </summary>
        internal static string TR0003_Description {
            get {
                return ResourceManager.GetString("TR0003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource-key &apos;{0}&apos; uses the generic format-parameter &apos;{1}&apos;. Consider to use a more meaningful name, instead. See {2}.
        /// </summary>
        internal static string TR0003_MessageFormat {
            get {
                return ResourceManager.GetString("TR0003_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an unrecognized parameter-type.
        /// </summary>
        internal static string TR0004_Description {
            get {
                return ResourceManager.GetString("TR0004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource-key &apos;{0}&apos; uses unrecognized parameter-annotation &apos;{1}&apos;. Falling back to &apos;object&apos;. See {2}.
        /// </summary>
        internal static string TR0004_MessageFormat {
            get {
                return ResourceManager.GetString("TR0004_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberName would be un-compilable.
        /// </summary>
        internal static string TR0005_Description {
            get {
                return ResourceManager.GetString("TR0005_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource-key &apos;{0}&apos; reduced to &apos;{1}&apos; would be non-compilable. Falling back to &apos;{2}&apos;. See {3}.
        /// </summary>
        internal static string TR0005_MessageFormat {
            get {
                return ResourceManager.GetString("TR0005_MessageFormat", resourceCulture);
            }
        }
    }
}
