//HintName: TypealizR.Tests.CodeFirst.Translatables.g.cs
// <auto-generated/>
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Localization;
namespace TypealizR.Tests.CodeFirst {
    [GeneratedCode("TypealizR.CodeFirstSourceGenerator", "1.0.0.0")]
    public partial class Translatables: ITranslatables {
        private readonly IStringLocalizer<ITranslatables> localizer;
        public Translatables (IStringLocalizer<ITranslatables> localizer) {
            this.localizer = localizer;
        }
        public LocalizedString Hello (string world) => localizer["Hello {0}", world];
        public LocalizedString Hello (string user, string world, int visitCount, bool dontPanic) => localizer["Hello {0} {1} {2} {3}", user, world, visitCount, dontPanic];
        public LocalizedString Greet (string user, DateTimeOffset now) => localizer["Hello {0}, the current time is: {1}", user, now];
        public LocalizedString Farewell (string user, DateTimeOffset now) => localizer["The current time is: {1}, Goodbye {0}", user, now];
        public LocalizedString Greeting {get; } => localizer["Greeting"];
        public LocalizedString CustomizedGreeting {get; } => localizer["Hello, fellow developer!"];
    }
}