//HintName: TypealizR.Tests.CodeFirst.IPublicInterface.g.cs
// <auto-generated/>
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Localization;
namespace TypealizR.Tests.CodeFirst {
    [GeneratedCode("TypealizR.CodeFirstSourceGenerator", "1.0.0.0")]
    public partial class PublicInterface: IPublicInterface {
        private readonly IStringLocalizer<IPublicInterface> localizer;
        public PublicInterface (IStringLocalizer<IPublicInterface> localizer) {
          this.localizer = localizer;
        }
        #region methods
        #region PublicHello-method
        public LocalizedString PublicHello_Raw
        {
            get
            {
              var localizedString = localizer[@"PublicHello"];
              if (!localizedString.ResourceNotFound)
              {
                  return localizedString;
              }
              return localizer[@"PublicHello {0}"];
            }
        }
        public LocalizedString PublicHello (string world)
        {
            var localizedString = localizer[@"PublicHello", world];
            if (!localizedString.ResourceNotFound)
            {
                return localizedString;
            }
          return localizer[@"PublicHello {0}", world];
        }
        #endregion
        #endregion
        #region properties
        #endregion
    }
}