//HintName: TypealizR.Tests.CodeFirst.Some_Outer_NestedClass_ITranslations.g.cs
// <auto-generated/>
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Localization;
namespace TypealizR.Tests.CodeFirst {
    partial class Some {
        partial class Outer {
            partial class NestedClass {
                [GeneratedCode("TypealizR.CodeFirst.CodeFirstSourceGenerator", "1.0.0.0")]
                internal partial class Translations: ITranslations {
                    private readonly IStringLocalizer<ITranslations> localizer;
                    public Translations (IStringLocalizer<ITranslations> localizer) {
                      this.localizer = localizer;
                    }
                    #region methods
                    #region typealized Hello
                    /// <summary>
                    /// Hello {0}
                    /// <summary>
                    public LocalizedString Hello_Raw
                    {
                        get
                        {
                          var localizedString = localizer["Hello"];
                          if (!localizedString.ResourceNotFound)
                          {
                              return localizedString;
                          }
                          return localizer[@"Hello {0}"];
                        }
                    }
                    /// <summary>
                    /// Hello {0}
                    /// <summary>
                    public LocalizedString Hello (string world)
                    {
                        var localizedString = localizer[@"Hello", world];
                        if (!localizedString.ResourceNotFound)
                        {
                            return localizedString;
                        }
                      return localizer[@"Hello {0}", world];
                    }
                    #endregion
                    #endregion
                    #region properties
                    #region typealized World
                    /// <summary>
                    /// World
                    /// <summary>
                    public LocalizedString World
                    {
                      get
                        {
                          var localizedString = localizer["World"];
                          if (!localizedString.ResourceNotFound)
                          {
                              return localizedString;
                          }
                          return localizer[@"World"];
                      }
                    }
                    #endregion
                    #endregion
                }
            }
        }
    }
}