//HintName: TypealizR.Tests.CodeFirst.IMembersWithSimpleXmlComment.g.cs
// <auto-generated/>
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Localization;
namespace TypealizR.Tests.CodeFirst {
    [GeneratedCode("TypealizR.CodeFirstSourceGenerator", "1.0.0.0")]
    internal partial class MembersWithSimpleXmlComment: IMembersWithSimpleXmlComment {
        private readonly IStringLocalizer<IMembersWithSimpleXmlComment> localizer;
        internal MembersWithSimpleXmlComment (IStringLocalizer<IMembersWithSimpleXmlComment> localizer) {
          this.localizer = localizer;
        }
        #region methods
        #region Hello-method
        private const string Hello_Key = @"Hello";
        private const string Hello_FallbackKey = @"Hello {0}!";
        public LocalizedString Hello_Raw
        {
            get
            {
              var localizedString = localizer[Hello_Key];
              if (!localizedString.ResourceNotFound)
              {
                  return localizedString;
              }
              return localizer[Hello_FallbackKey];
            }
        }
        public LocalizedString Hello (string world) 
        {
            var localizedString = localizer[Hello_Key, world];
            if (!localizedString.ResourceNotFound)
            {
                return localizedString;
            }
          return localizer[Hello_FallbackKey, world];
        }
        #endregion
        #endregion
        #region properties
        #region HelloProperty-property
        private const string HelloProperty_Key = @"HelloProperty";
        private const string HelloProperty_FallbackKey = @"Hello world!";
        public LocalizedString HelloProperty
        {
          get
            {
              var localizedString = localizer[HelloProperty_Key];
              if (!localizedString.ResourceNotFound)
              {
                  return localizedString;
              }
              return localizer[HelloProperty_FallbackKey];
          }
        }
        #endregion
        #region Greeting-property
        private const string Greeting_Key = @"Greeting";
        private const string Greeting_FallbackKey = @"Greetings, fellow developer!";
        public LocalizedString Greeting
        {
          get
            {
              var localizedString = localizer[Greeting_Key];
              if (!localizedString.ResourceNotFound)
              {
                  return localizedString;
              }
              return localizer[Greeting_FallbackKey];
          }
        }
        #endregion
        #region GreetingWithMultilineComment-property
        private const string GreetingWithMultilineComment_Key = @"GreetingWithMultilineComment";
        private const string GreetingWithMultilineComment_FallbackKey = @"Greetings, fellow developer!
 This line here will be in the generated default resource-key, also.
 And also this one, even with newlines #wowh@x0r!";
        public LocalizedString GreetingWithMultilineComment
        {
          get
            {
              var localizedString = localizer[GreetingWithMultilineComment_Key];
              if (!localizedString.ResourceNotFound)
              {
                  return localizedString;
              }
              return localizer[GreetingWithMultilineComment_FallbackKey];
          }
        }
        #endregion
        #endregion
    }
}