//HintName: TypealizR.Tests.CodeFirst.MembersWithSimpleXmlComment.g.cs
// <auto-generated/>
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Localization;
namespace TypealizR.Tests.CodeFirst {
    [GeneratedCode("TypealizR.CodeFirstSourceGenerator", "1.0.0.0")]
    public partial class MembersWithSimpleXmlComment: IMembersWithSimpleXmlComment {
        private readonly IStringLocalizer<IMembersWithSimpleXmlComment> localizer;
        public MembersWithSimpleXmlComment (IStringLocalizer<IMembersWithSimpleXmlComment> localizer) {
            this.localizer = localizer;
        }
        public LocalizedString Hello (string world) => localizer["Hello {0}", world];
        public LocalizedString HelloWorld { get; } => localizer["Hello world!"];
        public LocalizedString Greeting { get; } => localizer["Greetings, fellow developer!"];
    }
}