//HintName: TypealizR.Tests.CodeFirst.ITranslations.g.cs
// <auto-generated/>
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Localization;
namespace TypealizR.Tests.CodeFirst {
    partial class Some {
        partial class Outer {
            partial class NestedClass {
                [GeneratedCode("TypealizR.CodeFirstSourceGenerator", "1.0.0.0")]
                public partial class Translations: ITranslations {
                    private readonly IStringLocalizer<ITranslations> localizer;
                    public Translations (IStringLocalizer<ITranslations> localizer) {
                      this.localizer = localizer;
                    }
                    private const string Hello_Key = @"Hello";
                    private const string Hello_FallbackKey = @"Hello {0}";
                    public LocalizedString Hello_Raw => localizer[Hello_Key].Or(localizer[Hello_FallbackKey]);
                    public LocalizedString Hello (string world) => localizer[Hello_Key, world].Or(localizer[Hello_FallbackKey, world]);
                    private const string World_Key = @"World";
                    private const string World_FallbackKey = @"World";
                    public LocalizedString World => localizer[World_Key].Or(localizer[World_FallbackKey]);
                }
            }
        }
    }
}