//HintName: TypealizR.Tests.CodeFirst.MethodsWithXmlCommentParameters.g.cs
// <auto-generated/>
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Extensions.Localization;
namespace TypealizR.Tests.CodeFirst {
    [GeneratedCode("TypealizR.CodeFirstSourceGenerator", "1.0.0.0")]
    public partial class MethodsWithXmlCommentParameters: IMethodsWithXmlCommentParameters {
        private readonly IStringLocalizer<IMethodsWithXmlCommentParameters> localizer;
        public MethodsWithXmlCommentParameters (IStringLocalizer<IMethodsWithXmlCommentParameters> localizer) {
            this.localizer = localizer;
        }
        public LocalizedString Greet (string user, DateTimeOffset now) => localizer["Hello {0}, the current time is: {1}", user, now];
        public LocalizedString Farewell (string user, DateTimeOffset now) => localizer["The current time is: {1}, goodbye '{0}'", user, now];
    }
}