//HintName: StringTypealizR_Some.Root.Namespace.Groupings_NoCode.g.cs
// <auto-generated/>
using TypealizR.Abstractions;
using Some.Root.Namespace;
namespace Some.Root.Namespace.TypealizR
{

    [GeneratedCode("TypealizR.StringTypealizRSourceGenerator", "1.0.0.0")]
    internal partial class StringTypealizR_Some_Root_Namespace_Groupings_NoCode : IStringTypealizR<Groupings_NoCode>
    {

        private readonly IStringLocalizer<Groupings_NoCode> localizer;
        public StringTypealizR_Some_Root_Namespace_Groupings_NoCode(IStringLocalizer<Groupings_NoCode> localizer)
        {
            this.localizer = localizer;
            Log = new LogGroup(localizer);
            Question = new QuestionGroup(localizer);
            Warning = new WarningGroup(localizer);
        }

        /// <summary>
        /// Looks up a localized string similar to 'Greetings {name}, today is {date}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Greetings {0}, today is {1}'
        /// </returns>
        public LocalizedString Greetings__name__today_is__date(object name, object date)
            => localizer["Greetings {name}, today is {date}"].Format(name, date);

        /// <summary>
        /// Looks up a localized string similar to 'Hello'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Hello'
        /// </returns>
        public LocalizedString Hello
            => localizer["Hello"];

        /// <summary>
        /// Looks up a localized string similar to 'Hello {name:s}, today is {date:d}'
        /// </summary>
        /// <returns>
        /// A localized version of the current default value of 'Hello {0}, today is {1}'
        /// </returns>
        public LocalizedString Hello__name__today_is__date(string name, DateOnly date)
            => localizer["Hello {name:s}, today is {date:d}"].Format(name, date);
        
        public LogGroup Log { get; }
        public QuestionGroup Question { get; }
        public WarningGroup Warning { get; }

        [GeneratedCode("TypealizR.StringTypealizRSourceGenerator", "1.0.0.0")]
        internal partial class LogGroup
        {

            private readonly IStringLocalizer<Groupings_NoCode> localizer;
            [DebuggerStepThrough]
            public LogGroup(IStringLocalizer<Groupings_NoCode> localizer)
            {
                this.localizer = localizer;
                Critical = new CriticalGroup(localizer);
                Warning = new WarningGroup(localizer);
            }

        
            public CriticalGroup Critical { get; }
            public WarningGroup Warning { get; }

            [GeneratedCode("TypealizR.StringTypealizRSourceGenerator", "1.0.0.0")]
            internal partial class CriticalGroup
            {

                private readonly IStringLocalizer<Groupings_NoCode> localizer;
                [DebuggerStepThrough]
                public CriticalGroup(IStringLocalizer<Groupings_NoCode> localizer)
                {
                    this.localizer = localizer;
            
                }

                /// <summary>
                 /// Looks up a localized string similar to '[Log.Critical]: Failed to delete {UserName:s}'
                /// </summary>
                /// <returns>
                /// A localized version of the current default value of 'Failed to delete {0}'
                /// </returns>
                public LocalizedString Failed_to_delete__UserName(string UserName)
                    => localizer["[Log.Critical]: Failed to delete {UserName:s}"].Format(UserName);
            

            
            }
            
            [GeneratedCode("TypealizR.StringTypealizRSourceGenerator", "1.0.0.0")]
            internal partial class WarningGroup
            {

                private readonly IStringLocalizer<Groupings_NoCode> localizer;
                [DebuggerStepThrough]
                public WarningGroup(IStringLocalizer<Groupings_NoCode> localizer)
                {
                    this.localizer = localizer;
                
                }

                /// <summary>
                /// Looks up a localized string similar to '[Log.Warning]: Could not find {UserName:s}'
                /// </summary>
                /// <returns>
                /// A localized version of the current default value of 'Could not find {0}'
                /// </returns>
                public LocalizedString Could_not_find__UserName(string UserName)
                    => localizer["[Log.Warning]: Could not find {UserName:s}"].Format(UserName);

                /// <summary>
                /// Looks up a localized string similar to '[Log.Warning]: Unknown error'
                /// </summary>
                /// <returns>
                /// A localized version of the current default value of 'Encountered an unknown error during the operation'
                /// </returns>
                public LocalizedString Unknown_error
                    => localizer["[Log.Warning]: Unknown error"];
            

            
            }
        }
        
        [GeneratedCode("TypealizR.StringTypealizRSourceGenerator", "1.0.0.0")]
        internal partial class QuestionGroup
        {

            private readonly IStringLocalizer<Groupings_NoCode> localizer;
            [DebuggerStepThrough]
            public QuestionGroup(IStringLocalizer<Groupings_NoCode> localizer)
            {
                this.localizer = localizer;
                
            }

            /// <summary>
            /// Looks up a localized string similar to '[Question]: Abort ?'
            /// </summary>
            /// <returns>
            /// A localized version of the current default value of 'Abort?'
            /// </returns>
            public LocalizedString Abort
                => localizer["[Question]: Abort ?"];

            /// <summary>
            /// Looks up a localized string similar to '[Question]: Continue to delete {UserName:s}?'
            /// </summary>
            /// <returns>
            /// A localized version of the current default value of 'Continue to delete {0}?'
            /// </returns>
            public LocalizedString Continue_to_delete__UserName(string UserName)
                => localizer["[Question]: Continue to delete {UserName:s}?"].Format(UserName);
        

        
        }
        
        [GeneratedCode("TypealizR.StringTypealizRSourceGenerator", "1.0.0.0")]
        internal partial class WarningGroup
        {

            private readonly IStringLocalizer<Groupings_NoCode> localizer;
            [DebuggerStepThrough]
            public WarningGroup(IStringLocalizer<Groupings_NoCode> localizer)
            {
                this.localizer = localizer;
                
            }

            /// <summary>
            /// Looks up a localized string similar to '[Warning]: {UserName:s} will be deleted!'
            /// </summary>
            /// <returns>
            /// A localized version of the current default value of '{0} will be deleted'
            /// </returns>
            public LocalizedString UserName__will_be_deleted(string UserName)
                => localizer["[Warning]: {UserName:s} will be deleted!"].Format(UserName);
        

        
        }

    }
}
