//HintName: IStringLocalizerExtensions_Some.Root.Namespace.Groupings_NoCode.g.cs
// <auto-generated/>
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using TypealizR.Abstractions;

namespace Microsoft.Extensions.Localization
{
	[GeneratedCode("TypealizR.StringLocalizerSourceGenerator", "1.0.0.0")]
	internal class GroupedStringLocalizer_Some_Root_Namespace_Groupings_NoCode_WithGroups : IGroupedStringLocalizer<Some.Root.Namespace.Groupings_NoCode>
	{
		private readonly IStringLocalizer<Some.Root.Namespace.Groupings_NoCode> that;

		[GeneratedCode("TypealizR.StringLocalizerSourceGenerator", "1.0.0.0")]
		internal partial class LogGroup
		{
			private readonly IStringLocalizer that;

			private readonly Lazy<CriticalGroup> _Critical;
			private readonly Lazy<CriticalGroup> _Warning;

			[DebuggerStepThrough]
			public LogGroup(IStringLocalizer that)
			{
				this.that = that;
				_Critical = new(() => new(that));
				_Warning = new(() => new(that));
			}

			[GeneratedCode("TypealizR.StringLocalizerSourceGenerator", "1.0.0.0")]
			internal class CriticalGroup
			{
				private readonly IStringLocalizer that;

				[DebuggerStepThrough]
				public CriticalGroup(IStringLocalizer that)
				{
					this.that = that;
				}

				/// <summary>
				/// Looks up a localized string similar to 'Failed to delete {UserName:s}'
				/// </summary>
				/// <returns>
				/// A localized version of the current default value of 'Failed to delete {0}'
				/// </returns>
				[DebuggerStepThrough]
				public LocalizedString Failed_to_delete__UserName(string UserName)
					=> that["[Log.Critical] Failed to delete {UserName:s}"].Format(UserName);
			}

			[GeneratedCode("TypealizR.StringLocalizerSourceGenerator", "1.0.0.0")]
			internal class Warning
			{
				private readonly IStringLocalizer that;

				[DebuggerStepThrough]
				public Warning(IStringLocalizer that)
				{
					this.that = that;
				}

				/// <summary>
				/// Looks up a localized string similar to 'Could not find {UserName:s}'
				/// </summary>
				/// <returns>
				/// A localized version of the current default value of 'Could not find {0}'
				/// </returns>
				[DebuggerStepThrough]
				public LocalizedString Could_not_find__UserName(string UserName)
					=> that["[Log.Warning] Could not find {UserName:s}"].Format(UserName);

				/// <summary>
				/// Looks up a localized string similar to 'Unknown error'
				/// </summary>
				/// <returns>
				/// A localized version of the current default value of 'Encountered an unknown error during the operation'
				/// </returns>
				[DebuggerStepThrough]
				public LocalizedString Unknown_error(this IStringLocalizer<Some.Root.Namespace.Groupings_NoCode> that)
					=> that["[Log.Warning] Unknown error"];
			}
		}

		[GeneratedCode("TypealizR.StringLocalizerSourceGenerator", "1.0.0.0")]
		internal partial class QuestionGroup
		{
			private readonly IStringLocalizer that;

			[DebuggerStepThrough]
			public QuestionGroup(IStringLocalizer that)
			{
				this.that = that;
			}

			/// <summary>
			/// Looks up a localized string similar to 'Continue to delete {UserName:s}?'
			/// </summary>
			/// <returns>
			/// A localized version of the current default value of 'Continue to delete {0}?'
			/// </returns>
			[DebuggerStepThrough]
			public LocalizedString Continue_to_delete__UserName(string UserName)
			=> that["[Question] Continue to delete {UserName:s}?"].Format(UserName);
		}

		[GeneratedCode("TypealizR.StringLocalizerSourceGenerator", "1.0.0.0")]
		internal partial class WarningGroup
		{
			private readonly IStringLocalizer that;

			[DebuggerStepThrough]
			public WarningGroup(IStringLocalizer that)
			{
				this.that = that;
			}

			/// <summary>
			/// Looks up a localized string similar to '{UserName:s} will be deleted!'
			/// </summary>
			/// <returns>
			/// A localized version of the current default value of '{0} will be deleted'
			/// </returns>
			[DebuggerStepThrough]
			public static LocalizedString UserName__will_be_deleted(this IStringLocalizer<Some.Root.Namespace.Groupings_NoCode> that, string UserName)
				=> that["[Warning] {UserName:s} will be deleted!"].Format(UserName);
		}

		public Some_Root_Namespace_Groupings_NoCode_WithGroups(IStringLocalizer<Some.Root.Namespace.Groupings_NoCode> that)
		{
			this.that = that;
			Question = new(that);
			Log = new(that);
			Warning = new(that);
		}

		public QuestionGroup Question { get; }

		public LogGroup Log { get; }

		public WarningGroup Warning { get; }
	}
}

namespace Microsoft.Extensions.Localization
{
	[GeneratedCode("TypealizR.StringLocalizerSourceGenerator", "1.0.0.0")]
	internal static partial class IStringLocalizerExtensions_Some_Root_Namespace_Groupings_NoCode_WithGroups
	{
		[DebuggerStepThrough]
		public static GroupedStringLocalizer_Some_Root_Namespace_Groupings_NoCode_WithGroups WithGroups(this IStringLocalizer<Some.Root.Namespace.Groupings_NoCode> that)
			=> new(that);
	}
}